version: '3.5'

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/christina/data/www
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/christina/data/mysql

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/
    depends_on:
      - wordpress
    networks:
      - inception-net
    restart: on-failure
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/
    networks:
      - inception-net
    depends_on:
      - mariadb
    restart: on-failure
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-net
    restart: on-failure

networks:
  inception-net:
    driver: bridge