version: '3.5'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/crepou/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/crepou/data/mariadb

services:
  nginx:
    build: ./nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception-net
    restart: always
  wordpress:
    build: ./wordpress/.
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-net
    depends_on:
      - mariadb
    restart: always
  mariadb:
    build: ./mariadb/.
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-net
    restart: always

networks:
  inception-net:
    driver: bridge